[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nrai-pathplanning"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.0",
    "scipy>=1.18.0",
]
[project.scripts]
nrai_pathplanning = "nrai_pathplanning:main"
